---

- name: add ppa
  become: true
  apt_repository:
    repo: "{{ php_ppa }}"
    state: present

- name: install php
  become: true
  apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-iconv"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-dev"
      - libapache2-mod-php
      - composer
