---

- name: add nodejs apt key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add nodejs apt repository
  become: true
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_12.x bionic main'
    update_cache: true

- name: install nodejs
  become: true
  apt:
    name: nodejs
    state: present
